# Generated by Django 6.0.7 on 2026-08-04 20:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('nom', models.CharField(max_length=60)),
                ('prenom', models.CharField(max_length=100)),
                ('nom_utilisateur', models.CharField(max_length=70, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telephone', models.CharField(blank=True, max_length=15, null=True, unique=True)),
                ('date_naissance', models.DateField(blank=True, null=True)),
                ('role', models.CharField(choices=[('candidat', 'Candidat'), ('recruteur', 'Recruteur'), ('administrateur', 'Administrateur')], default='candidat', max_length=20)),
                ('photo_profil', models.ImageField(blank=True, null=True, upload_to='photo_profil/')),
                ('date_incription', models.DateTimeField(auto_now_add=True)),
                ('statut_compte', models.CharField(choices=[('actif', 'Actif'), ('desactive_utilisateur', "Désactivé par l'utilisateur"), ('suspendu_admin', "Suspendu par l'administrateur"), ('supprime', 'Supprimé')], default='actif', max_length=40)),
                ('date_Dernier_Connexion', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Utilisateur',
                'verbose_name_plural': 'Utilisateurs',
                'db_table': 'utilisateur',
            },
        ),
        migrations.CreateModel(
            name='Administrateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('utilisateur', models.OneToOneField(limit_choices_to={'role': 'administrateur'}, on_delete=django.db.models.deletion.CASCADE, related_name='administrateur', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Administrateur',
                'verbose_name_plural': 'Administrateurs',
                'db_table': 'administrateur',
            },
        ),
        migrations.CreateModel(
            name='Candidat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('localisation', models.CharField(max_length=100)),
                ('niveau_etude', models.CharField(max_length=100)),
                ('domaine_metier', models.CharField(max_length=100)),
                ('statut_recherche', models.BooleanField(default=True)),
                ('lien_linkdin', models.CharField(blank=True, max_length=200)),
                ('lien_porfolio', models.CharField(blank=True, max_length=200)),
                ('utilisateur', models.OneToOneField(limit_choices_to={'role': 'candidat'}, on_delete=django.db.models.deletion.CASCADE, related_name='candidat', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Candidat',
                'verbose_name_plural': 'Candidats',
                'db_table': 'candidat',
            },
        ),
        migrations.CreateModel(
            name='Recruteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poste', models.CharField(max_length=60)),
                ('utilisateur', models.OneToOneField(limit_choices_to={'role': 'recruteur'}, on_delete=django.db.models.deletion.CASCADE, related_name='recruteur', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Recruteur',
                'verbose_name_plural': 'Recruteurs',
                'db_table': 'recruteur',
            },
        ),
    ]
