# Generated by Django 6.0.7 on 2026-08-13 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidat',
            name='lien_linkdin',
        ),
        migrations.RemoveField(
            model_name='candidat',
            name='lien_porfolio',
        ),
        migrations.RemoveField(
            model_name='candidat',
            name='localisation',
        ),
        migrations.AddField(
            model_name='candidat',
            name='disponibilite',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='candidat',
            name='lien_linkedin',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='candidat',
            name='lien_portfolio',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='recruteur',
            name='compte_valide',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='email_verifie',
            field=models.BooleanField(default=False),
        ),
    ]
