# Generated by Django 6.0.7 on 2026-08-25 15:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_candidat_lien_linkdin_and_more'),
        ('entreprises', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruteur',
            name='entreprise',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='entreprises.entreprise', verbose_name='recruteur_entreprise'),
            preserve_default=False,
        ),
    ]
