# Generated by Django 6.0.7 on 2026-09-02 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_recruteur_entreprise'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidat',
            name='disponibilite',
        ),
        migrations.AlterField(
            model_name='candidat',
            name='niveau_etude',
            field=models.CharField(blank=True, choices=[('bac', 'Baccalauréat'), ('bac2', 'Bac +2 / BTS'), ('bac3', 'Bac +3 / Licence'), ('bac4', 'Bac +4'), ('bac5', 'Bac +5 / Master'), ('doctorat', 'Doctorat'), ('autre', 'Autre')], max_length=20, null=True),
        ),
    ]
