# Generated by Django 6.0.7 on 2026-09-02 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_candidat_disponibilite_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidat',
            name='disponibilite',
            field=models.DateField(blank=True, null=True),
        ),
    ]
