# Generated by Django 6.0.7 on 2026-08-25 15:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entreprise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raison_sociale', models.CharField(max_length=150)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='entreprises/logos/')),
                ('banniere', models.ImageField(blank=True, null=True, upload_to='entreprises/bannieres/')),
                ('description', models.TextField(blank=True, help_text="Présentation générale de l'entreprise", null=True)),
                ('secteur_activite', models.CharField(choices=[('administration', 'Administration publique'), ('agriculture', 'Agriculture / Agroalimentaire'), ('automobile', 'Automobile'), ('banque', 'Banque / Finance / Assurance'), ('btp', 'BTP / Construction'), ('commerce', 'Commerce / Distribution'), ('communication', 'Communication / Publicité / Marketing'), ('conseil', 'Conseil / Consulting'), ('culture', 'Culture / Arts / Divertissement'), ('education', 'Éducation / Formation'), ('energie', 'Énergie / Pétrole / Gaz'), ('environnement', 'Environnement / Développement durable'), ('industrie', 'Industrie / Manufacturière'), ('informatique', 'Informatique / Technologies'), ('immobilier', 'Immobilier'), ('juridique', 'Juridique / Droit'), ('logistique', 'Logistique / Transport'), ('medias', 'Médias / Audiovisuel'), ('mines', 'Mines / Industries extractives'), ('pharmaceutique', 'Pharmaceutique'), ('peche', 'Pêche / Aquaculture'), ('restauration', 'Restauration / Gastronomie'), ('sante', 'Santé'), ('securite', 'Sécurité / Défense'), ('services_entreprises', 'Services aux entreprises'), ('services_personne', 'Services à la personne'), ('sport', 'Sport / Loisirs'), ('telecommunication', 'Télécommunications'), ('tourisme', 'Tourisme / Hôtellerie'), ('ong', 'ONG / Associations / Humanitaire'), ('autre', 'Autre')], default='autre', max_length=30)),
                ('taille_effectif', models.CharField(blank=True, choices=[('tpe', '1 à 9 salariés'), ('pe', '10 à 49 salariés'), ('pme', '50 à 249 salariés'), ('eti', '250 à 999 salariés'), ('ge', '1000 salariés et plus')], max_length=10, null=True)),
                ('date_creation_entreprise', models.DateField(blank=True, help_text="Date de création/fondation de l'entreprise", null=True)),
                ('ninea', models.CharField(blank=True, help_text="Numéro d'Identification Nationale des Entreprises et Associations", max_length=20, null=True, unique=True, verbose_name='NINEA')),
                ('registre_commerce', models.CharField(blank=True, max_length=30, null=True, verbose_name='Registre de commerce (RCCM)')),
                ('email_contact', models.EmailField(blank=True, max_length=254, null=True)),
                ('telephone', models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='Numéro de téléphone invalide', regex='^\\+?[0-9\\s]{7,20}$')])),
                ('site_web', models.URLField(blank=True, null=True, validators=[django.core.validators.URLValidator()])),
                ('linkedin_url', models.URLField(blank=True, null=True)),
                ('adresse', models.CharField(blank=True, max_length=255, null=True)),
                ('ville', models.CharField(blank=True, max_length=50, null=True)),
                ('pays', models.CharField(default='Sénégal', max_length=50)),
                ('statut_verification', models.CharField(choices=[('en_attente', 'En attente de vérification'), ('verifiee', 'Vérifiée'), ('rejetee', 'Rejetée')], default='en_attente', max_length=20)),
                ('date_verification', models.DateTimeField(blank=True, null=True)),
                ('est_active', models.BooleanField(default=True, help_text='Permet de désactiver un compte entreprise sans le supprimer')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Entreprise',
                'verbose_name_plural': 'Entreprises',
                'db_table': 'entreprise',
                'ordering': ['raison_sociale'],
            },
        ),
    ]
