# Generated by Django 6.0.7 on 2026-08-25 15:11

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_recruteur_entreprise'),
    ]

    operations = [
        migrations.CreateModel(
            name='CV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chemin_fichier', models.FileField(blank=True, null=True, upload_to='cv/')),
                ('nom_fichier_original', models.CharField(max_length=50)),
                ('taille_fichier', models.IntegerField(help_text='Taille du fichier en octets', validators=[django.core.validators.MinValueValidator(0)])),
                ('texte_extrait', models.TextField(blank=True, null=True)),
                ('langue', models.CharField(blank=True, max_length=50, null=True)),
                ('statut_traitement', models.CharField(choices=[('en_attente', 'En attente'), ('en_cours', "En cours d'analyse"), ('termine', 'Analyse terminée'), ('echec', "Échec de l'analyse")], default='en_attente', max_length=20)),
                ('date_upload', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('candidat', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cv', to='accounts.candidat', verbose_name='candidat')),
            ],
            options={
                'verbose_name': 'CV',
                'verbose_name_plural': 'CVs',
                'db_table': 'cv',
                'ordering': ['-date_upload'],
            },
        ),
        migrations.CreateModel(
            name='Competence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('categorie', models.CharField(choices=[('technique', 'Compétence technique'), ('langue', 'Langue'), ('soft_skill', 'Savoir-être'), ('outil', 'Outil / Logiciel'), ('certification', 'Certification')], default='technique', max_length=20)),
                ('niveau', models.CharField(blank=True, choices=[('debutant', 'Débutant'), ('intermediaire', 'Intermédiaire'), ('avance', 'Avancé'), ('expert', 'Expert')], max_length=20, null=True)),
                ('annees_experience', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('cv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competences', to='candidats.cv', verbose_name='cv')),
            ],
            options={
                'verbose_name': 'Compétence',
                'verbose_name_plural': 'Compétences',
                'db_table': 'competence',
                'ordering': ['categorie', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poste', models.CharField(max_length=50)),
                ('nom_entreprise', models.CharField(max_length=50)),
                ('secteur', models.CharField(blank=True, max_length=50, null=True)),
                ('localisation', models.CharField(blank=True, max_length=50, null=True)),
                ('type_contrat', models.CharField(blank=True, choices=[('cdi', 'CDI'), ('cdd', 'CDD'), ('stage', 'Stage'), ('freelance', 'Freelance'), ('alternance', 'Alternance'), ('benevolat', 'Bénévolat')], max_length=20, null=True)),
                ('description', models.TextField(blank=True, help_text='Description des missions et responsabilités', null=True)),
                ('niveau_seniorite', models.CharField(blank=True, help_text='Ex: Junior, Confirmé, Senior, Manager', max_length=50, null=True)),
                ('en_cours', models.BooleanField(default=False)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField(blank=True, help_text="Laisser vide si l'expérience est en cours", null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('competences_utilisees', models.ManyToManyField(blank=True, related_name='experiences', to='candidats.competence')),
                ('cv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiences', to='candidats.cv', verbose_name='cv')),
            ],
            options={
                'verbose_name': 'Expérience',
                'verbose_name_plural': 'Expériences',
                'db_table': 'experience',
                'ordering': ['-date_debut'],
            },
        ),
        migrations.CreateModel(
            name='Formation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intitule', models.CharField(help_text='Intitulé du diplôme', max_length=100)),
                ('etablissement', models.CharField(max_length=100)),
                ('domaine_etude', models.CharField(blank=True, max_length=100, null=True)),
                ('niveau_diplome', models.CharField(blank=True, choices=[('bac', 'Baccalauréat'), ('bac_2', 'Bac+2 (BTS/DUT)'), ('licence', 'Licence / Bac+3'), ('master', 'Master / Bac+5'), ('doctorat', 'Doctorat'), ('autre', 'Autre')], max_length=20, null=True)),
                ('ville', models.CharField(blank=True, max_length=50, null=True)),
                ('pays', models.CharField(blank=True, max_length=50, null=True)),
                ('mention', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('en_cours', models.BooleanField(default=False)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField(blank=True, help_text='Laisser vide si la formation est en cours', null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('cv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formations', to='candidats.cv', verbose_name='cv')),
            ],
            options={
                'verbose_name': 'Formation',
                'verbose_name_plural': 'Formations',
                'db_table': 'formation',
                'ordering': ['-date_debut'],
            },
        ),
        migrations.CreateModel(
            name='Preference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secteurs_preferes', models.JSONField(blank=True, default=list, help_text="Liste des secteurs d'activité recherchés (ex: technologie, finance...)")),
                ('type_contrat_prefere', models.CharField(choices=[('cdi', 'CDI'), ('cdd', 'CDD'), ('stage', 'Stage'), ('freelance', 'Freelance'), ('alternance', 'Alternance'), ('indifferent', 'Indifférent')], default='indifferent', max_length=20)),
                ('salaire_min_souhaite', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('niveau_poste_souhaite', models.CharField(blank=True, choices=[('stagiaire', 'Stagiaire'), ('junior', 'Junior'), ('confirme', 'Confirmé'), ('senior', 'Senior'), ('manager', "Manager / Chef d'équipe"), ('direction', 'Direction')], max_length=20, null=True)),
                ('date_maj', models.DateField(auto_now=True)),
                ('mode_travail', models.CharField(choices=[('presentiel', 'Présentiel'), ('teletravail', 'Télétravail'), ('hybride', 'Hybride'), ('indifferent', 'Indifférent')], default='indifferent', max_length=20)),
                ('niveau_experience_recherchee', models.CharField(blank=True, choices=[('debutant', 'Débutant (0-2 ans)'), ('junior', 'Junior (2-5 ans)'), ('confirme', 'Confirmé (5-10 ans)'), ('senior', 'Senior (10+ ans)')], max_length=20, null=True)),
                ('villes_preferees', models.JSONField(blank=True, default=list, help_text='Villes où le candidat souhaite travailler')),
                ('mots_cles', models.CharField(blank=True, help_text="Mots-clés libres utilisés pour affiner les suggestions d'offres", max_length=255, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('candidat', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preference', to='accounts.candidat', verbose_name='candidat')),
            ],
            options={
                'verbose_name': 'Préférence',
                'verbose_name_plural': 'Préférences',
                'db_table': 'preference',
            },
        ),
    ]
