# Generated by Django 6.0.7 on 2026-08-25 15:11

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_recruteur_entreprise'),
        ('offres', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recommandation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score_matching', models.FloatField(help_text="Score de compatibilité candidat/offre calculé par l'IA (0 à 100)", validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('raison', models.TextField(blank=True, help_text="Explication générée par l'IA sur la pertinence de cette recommandation", null=True)),
                ('statut', models.CharField(choices=[('nouvelle', 'Nouvelle'), ('vue', 'Vue par le candidat'), ('ignoree', 'Ignorée'), ('postulee', 'A conduit à une candidature')], default='nouvelle', max_length=20)),
                ('date_recommandation', models.DateTimeField(auto_now_add=True)),
                ('date_consultation', models.DateTimeField(blank=True, null=True)),
                ('candidat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommandations', to='accounts.candidat', verbose_name='candidat')),
                ('offre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommandations', to='offres.offreemploi', verbose_name="offre d'emploi")),
            ],
            options={
                'verbose_name': 'Recommandation',
                'verbose_name_plural': 'Recommandations',
                'db_table': 'recommandation',
                'ordering': ['-score_matching', '-date_recommandation'],
                'unique_together': {('candidat', 'offre')},
            },
        ),
    ]
