# Generated by Django 6.0.7 on 2026-08-25 15:11

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entretien',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('format', models.CharField(choices=[('presentiel', 'Présentiel'), ('visio', 'Visioconférence'), ('telephonique', 'Téléphonique')], max_length=50)),
                ('statut', models.CharField(choices=[('planifie', 'Planifié'), ('confirme', 'Confirmé'), ('annule', 'Annulé'), ('termine', 'Terminé'), ('reprogramme', 'Reprogrammé')], default='planifie', max_length=50)),
                ('lienVisio', models.CharField(blank=True, max_length=255, null=True)),
                ('adresseLieu', models.CharField(blank=True, max_length=255, null=True)),
                ('rappelEnvoye', models.BooleanField(default=False)),
                ('noteRecruteur', models.CharField(blank=True, max_length=255, null=True)),
                ('dateHeure', models.DateTimeField()),
                ('dateCreation', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Entretien',
                'verbose_name_plural': 'Entretiens',
                'ordering': ['-dateHeure'],
            },
        ),
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('noteGlobale', models.IntegerField(blank=True, null=True)),
                ('commentaireGlobale', models.TextField(blank=True, null=True)),
                ('pointForts', models.TextField(blank=True, null=True)),
                ('pointAmeliorer', models.TextField(blank=True, null=True)),
                ('decision', models.CharField(choices=[('favorable', 'Favorable'), ('defavorable', 'Défavorable'), ('en_attente', 'En attente')], default='en_attente', max_length=50)),
                ('dateEvaluation', models.DateTimeField(default=django.utils.timezone.now)),
                ('entretien', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='evaluation', to='entretien.entretien', verbose_name='Entretien concerné')),
            ],
            options={
                'verbose_name': 'Evaluation',
                'verbose_name_plural': 'Evaluations',
                'ordering': ['-dateEvaluation'],
            },
        ),
        migrations.CreateModel(
            name='CritereEvaluation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('libelle', models.CharField(max_length=255)),
                ('categorie', models.CharField(blank=True, max_length=100, null=True)),
                ('note', models.IntegerField()),
                ('noteMax', models.IntegerField(default=10)),
                ('commentaire', models.TextField(blank=True, null=True)),
                ('evaluation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criteres', to='entretien.evaluation', verbose_name='Evaluation associée')),
            ],
            options={
                'verbose_name': "Critère d'évaluation",
                'verbose_name_plural': "Critères d'évaluation",
            },
        ),
    ]
