# Generated by Django 6.0.7 on 2026-08-25 15:11

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_recruteur_entreprise'),
        ('offres', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lettre_motivation', models.FileField(blank=True, null=True, upload_to='candidature/lettre_motivation/')),
                ('message_candidat', models.TextField(blank=True, help_text='Message libre accompagnant la candidature', null=True)),
                ('score_matching', models.FloatField(blank=True, help_text="Score de compatibilité candidat/offre calculé par l'IA (0 à 100)", null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('analyse_ia', models.TextField(blank=True, help_text="Synthèse générée par l'IA sur l'adéquation candidat/offre", null=True)),
                ('points_forts', models.TextField(blank=True, help_text="Points forts identifiés par l'IA", null=True)),
                ('points_faibles', models.TextField(blank=True, help_text="Écarts identifiés par l'IA par rapport à l'offre", null=True)),
                ('statut', models.CharField(choices=[('envoyee', 'Envoyée'), ('vue', 'Vue par le recruteur'), ('preselectionnee', 'Présélectionnée'), ('entretien', 'Entretien programmé'), ('acceptee', 'Acceptée'), ('refusee', 'Refusée'), ('retiree', 'Retirée par le candidat')], default='envoyee', max_length=20)),
                ('note_recruteur', models.TextField(blank=True, help_text='Notes internes du recruteur, non visibles du candidat', null=True)),
                ('est_favorite', models.BooleanField(default=False, help_text='Marquée comme favorite par le recruteur')),
                ('score_competences', models.FloatField(blank=True, null=True)),
                ('score_experience', models.FloatField(blank=True, null=True)),
                ('score_formation', models.FloatField(blank=True, null=True)),
                ('score_global', models.FloatField(blank=True, null=True)),
                ('date_candidature', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('candidat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidatures', to='accounts.candidat', verbose_name='candidat')),
                ('offre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidatures', to='offres.offreemploi', verbose_name="offre d'emploi")),
            ],
            options={
                'verbose_name': 'Candidature',
                'verbose_name_plural': 'Candidatures',
                'db_table': 'candidature',
                'ordering': ['-date_candidature'],
                'unique_together': {('candidat', 'offre')},
            },
        ),
        migrations.CreateModel(
            name='PieceJointe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fichier', models.FileField(upload_to='pieces_jointes/')),
                ('nom_fichier_original', models.CharField(max_length=100)),
                ('type_piece', models.CharField(choices=[('portfolio', 'Portfolio'), ('diplome', 'Diplôme / Certificat'), ('recommandation', 'Lettre de recommandation'), ('autre', 'Autre')], default='autre', max_length=30)),
                ('taille_fichier', models.IntegerField(help_text='Taille du fichier en octets', validators=[django.core.validators.MinValueValidator(0)])),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('candidature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pieces_jointes', to='candidatures.candidature', verbose_name='candidature')),
            ],
            options={
                'verbose_name': 'Pièce jointe',
                'verbose_name_plural': 'Pièces jointes',
                'db_table': 'piece_jointe',
                'ordering': ['-date_ajout'],
            },
        ),
    ]
