# Generated by Django 6.0.7 on 2026-08-25 15:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_recruteur_entreprise'),
        ('entreprises', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OffreEmploi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=150)),
                ('description', models.TextField(help_text='Description générale du poste')),
                ('missions', models.TextField(blank=True, null=True)),
                ('profil_recherche', models.TextField(blank=True, help_text='Profil, qualités et prérequis attendus', null=True)),
                ('avantages', models.TextField(blank=True, null=True)),
                ('type_contrat', models.CharField(choices=[('cdi', 'CDI'), ('cdd', 'CDD'), ('stage', 'Stage'), ('freelance', 'Freelance'), ('alternance', 'Alternance'), ('interim', 'Intérim')], max_length=20)),
                ('niveau_experience', models.CharField(blank=True, choices=[('debutant', 'Débutant'), ('junior', '1 à 2 ans'), ('intermediaire', '3 à 5 ans'), ('senior', '5 à 10 ans'), ('expert', 'Plus de 10 ans')], max_length=20, null=True)),
                ('niveau_etudes', models.CharField(blank=True, choices=[('aucun', 'Aucun diplôme requis'), ('bac', 'Baccalauréat'), ('bac2', 'Bac +2 / BTS'), ('bac3', 'Bac +3 / Licence'), ('bac4', 'Bac +4'), ('bac5', 'Bac +5 / Master'), ('doctorat', 'Doctorat')], max_length=20, null=True)),
                ('mode_travail', models.CharField(choices=[('presentiel', 'Présentiel'), ('teletravail', 'Télétravail'), ('hybride', 'Hybride')], default='presentiel', max_length=20)),
                ('ville', models.CharField(blank=True, max_length=50, null=True)),
                ('pays', models.CharField(default='Sénégal', max_length=50)),
                ('salaire_min', models.PositiveIntegerField(blank=True, null=True)),
                ('salaire_max', models.PositiveIntegerField(blank=True, null=True)),
                ('devise', models.CharField(default='FCFA', max_length=10)),
                ('salaire_visible', models.BooleanField(default=False, help_text="Afficher la fourchette salariale sur l'offre publique")),
                ('nombre_postes', models.PositiveSmallIntegerField(default=1)),
                ('est_urgente', models.BooleanField(default=False)),
                ('poids_competence', models.PositiveIntegerField(blank=True, null=True)),
                ('poids_experience', models.PositiveIntegerField(blank=True, null=True)),
                ('poids_formation', models.PositiveIntegerField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('en_attente', 'En attente de validation'), ('publiee', 'Publiée'), ('expiree', 'Expirée'), ('pourvue', 'Pourvue'), ('archivee', 'Archivée')], default='brouillon', max_length=20)),
                ('date_publication', models.DateTimeField(blank=True, null=True)),
                ('date_expiration', models.DateField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(blank=True, max_length=180, unique=True)),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offres', to='entreprises.entreprise', verbose_name='entreprise')),
                ('recruteur', models.ForeignKey(help_text="Recruteur ayant publié l'offre", on_delete=django.db.models.deletion.CASCADE, related_name='offres_publiees', to='accounts.recruteur', verbose_name='recruteur')),
            ],
            options={
                'verbose_name': "Offre d'emploi",
                'verbose_name_plural': "Offres d'emploi",
                'db_table': 'offre_emploi',
                'ordering': ['-date_publication', '-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='CompetenceRequise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('offre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competences_requises', to='offres.offreemploi', verbose_name='offre')),
            ],
            options={
                'verbose_name': 'Compétence requise',
                'verbose_name_plural': 'Compétences requises',
                'db_table': 'competence_requise',
                'ordering': ['nom'],
            },
        ),
    ]
